[
  {
    "id": "palo-alto-cortex-xpanse",
    "name": "Palo Alto Networks Cortex Xpanse",
    "url": "https://www.paloaltonetworks.com/cortex/cortex-xpanse",
    "cluster": "platform-consolidator",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["XSIAM", "XSOAR", "Cortex-XDR", "SIEM", "ITSM"],
    "description": "Cortex Xpanse is built on internet-scale infrastructure that scans over 500 billion ports daily, giving it genuine coverage breadth. Its core differentiator inside the Palo Alto ecosystem is the correlation layer: external exposure findings can be tied directly to endpoint, identity, and cloud telemetry inside Cortex XDR and XSIAM. For organizations already running Palo Alto as their primary security platform, that correlation is a meaningful operational advantage. For organizations that are not, the platform is expensive and the integration value evaporates. The 2026 launch of a Unified Exposure Management add-on signals intent to expand further into CTEM, though the architecture is still XDR-centric rather than exposure-program-centric.",
    "best_fit": "Large enterprises already standardized on the Palo Alto Cortex platform that want external attack surface discovery natively correlated with their existing endpoint and cloud telemetry.",
    "strengths": ["500B+ ports scanned daily — genuine coverage depth", "Native correlation with Cortex XDR and XSIAM telemetry", "Automated playbook integration via XSOAR"],
    "watch": "Platform lock-in is structural. ASM roadmap priorities are set by the broader Cortex platform, not by external discovery needs."
  },
  {
    "id": "crowdstrike-falcon-surface",
    "name": "CrowdStrike Falcon Surface",
    "url": "https://www.crowdstrike.com/products/exposure-management/falcon-surface/",
    "cluster": "platform-consolidator",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["Falcon-XDR", "Falcon-Identity", "SIEM", "SOAR", "ITSM"],
    "description": "Falcon Surface was built on the Reposify acquisition and integrated into the Falcon platform. Its distinguishing characteristic is the correlation between external asset discovery and CrowdStrike's endpoint and identity telemetry — an exposed external asset can be cross-referenced against whether it has a Falcon sensor installed, which identity credentials are associated with it, and what threat activity has been observed against it. Outside the CrowdStrike ecosystem, that value proposition collapses to a capable but undifferentiated EASM scanner. Best evaluated as a platform extension, not a standalone product.",
    "best_fit": "Organizations running CrowdStrike Falcon for endpoint and identity that want external attack surface visibility correlated with their existing telemetry without adding a new vendor.",
    "strengths": ["Cross-correlation between external exposure and Falcon endpoint and identity data", "Unified Falcon platform management", "Threat intelligence integration via CrowdStrike Intel"],
    "watch": "Discovery depth lags pure-play specialists for complex multi-subsidiary environments. Evaluate coverage against your specific infrastructure before committing."
  },
  {
    "id": "microsoft-defender-easm",
    "name": "Microsoft Defender EASM",
    "url": "https://www.microsoft.com/en-us/security/business/cloud-security/microsoft-defender-external-attack-surface-management",
    "cluster": "platform-consolidator",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["Defender-XDR", "Microsoft-Sentinel", "Azure-Security-Center", "ITSM"],
    "description": "Defender EASM is built on the RiskIQ acquisition and priced on a per-asset daily utilization model. The per-asset meter runs continuously — in large enterprise environments with dynamic cloud footprints or significant shadow IT, costs scale unpredictably. The Microsoft integration story is strongest when an organization is already deep in the Microsoft security stack — Sentinel as SIEM, Defender XDR as detection, Azure as cloud. Outside that environment, it is a functional EASM tool with moderate discovery depth.",
    "best_fit": "Enterprises standardized on the Microsoft security stack — Defender XDR, Sentinel, Azure — that want external asset discovery feeding directly into their existing detection and response workflows.",
    "strengths": ["Native integration with Defender XDR and Microsoft Sentinel", "RiskIQ internet data heritage provides solid discovery foundation", "Strong fit when Microsoft is the primary security platform"],
    "watch": "Per-asset daily pricing creates budget unpredictability in environments with dynamic cloud footprints or extensive shadow IT — model costs carefully before committing. Discovery coverage for complex multi-subsidiary environments lags pure-play specialists."
  },
  {
    "id": "tenable-asm",
    "name": "Tenable Attack Surface Management",
    "url": "https://www.tenable.com/products/attack-surface-management",
    "cluster": "vuln-ecosystem",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "full",
    "company_size": ["enterprise"],
    "integrations": ["Tenable-One", "Tenable-SC", "SIEM", "SOAR", "ITSM", "ServiceNow"],
    "description": "Tenable ASM is the external discovery layer of the Tenable One exposure management platform, which earned the Leader position in Gartner's inaugural Magic Quadrant for Exposure Assessment Platforms in November 2025 — the highest recognition in the category. The value proposition is a unified exposure view: external asset discovery from the internet combined with internal vulnerability data from Tenable's authenticated scanning, all scored and prioritized within a single platform. Tenable has made the most complete architectural commitment to CTEM among the vulnerability management incumbents, positioning Tenable One explicitly as an exposure management program rather than a scanning tool.",
    "best_fit": "Organizations already running Tenable for internal vulnerability management that want to extend into external discovery within a unified exposure management program, particularly those pursuing formal CTEM adoption.",
    "strengths": ["Gartner MQ Leader, Exposure Assessment Platforms (Nov 2025) — positioned highest for Ability to Execute and furthest for Completeness of Vision among the 20 vendors evaluated", "Unified internal and external exposure in Tenable One", "Most complete CTEM alignment among vuln management incumbents"],
    "watch": "External discovery depth for large, complex environments is strong but trails Censys in raw internet-scale coverage. Evaluate seedless discovery accuracy for your specific footprint."
  },
  {
    "id": "qualys-easm",
    "name": "Qualys EASM",
    "url": "https://www.qualys.com/apps/external-attack-surface-management/",
    "cluster": "vuln-ecosystem",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["Qualys-VMDR", "Qualys-CyberSecurity-Asset-Management", "SIEM", "ITSM", "ServiceNow"],
    "description": "Qualys EASM extends the Qualys vulnerability management platform outward, adding external asset discovery to an environment already built around authenticated internal scanning. It feeds discovered external assets into Qualys VMDR for unified risk scoring and into CSAM for asset inventory consolidation. The integration is tighter than most competitors offer within a single platform, but the external discovery engine reflects Qualys's authenticated-scanning roots more than a purpose-built seedless discovery architecture. Validation of exploitability on discovered external assets requires adjacent Qualys tools rather than being native to the EASM module.",
    "best_fit": "Organizations already running Qualys VMDR for internal vulnerability management that want external discovery integrated into their existing risk scoring and asset management workflows.",
    "strengths": ["Gartner MQ Leader, Exposure Assessment Platforms (Nov 2025)", "Tight integration with Qualys VMDR and CSAM", "Unified risk scoring across internal and external assets via TruRisk"],
    "watch": "External discovery completeness requires validation against your specific environment. Exploitability validation on external findings requires additional Qualys modules."
  },
  {
    "id": "rapid7-surface-command",
    "name": "Rapid7 Exposure Command",
    "url": "https://www.rapid7.com/products/command/exposure-management/",
    "cluster": "vuln-ecosystem",
    "asm_type": ["EASM", "CAASM"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["InsightVM", "InsightIDR", "Rapid7-SOAR", "SIEM", "ITSM"],
    "description": "Surface Command is Rapid7's unified attack surface product, combining external discovery (EASM) with internal asset aggregation (CAASM) in a single view. It ingests data from cloud providers, identity systems, and existing Rapid7 deployments alongside external internet scanning, giving it broader internal coverage than EASM-only competitors. The CAASM layer is a differentiator — most vulnerability management vendors have prioritized external discovery and left internal aggregation as a secondary capability. Integration with InsightIDR and Rapid7 SOAR closes the loop from discovery to detection and response within the Rapid7 ecosystem.",
    "best_fit": "Organizations running Rapid7 for vulnerability management and detection that want unified internal and external asset visibility within a single platform.",
    "strengths": ["Gartner MQ Leader, Exposure Assessment Platforms (Nov 2025)", "Combined EASM and CAASM in one product — broader than most vuln management extensions", "Integration with InsightIDR for detection correlation"],
    "watch": "External discovery depth trails pure-play specialists. Evaluate internet-scale coverage for environments with complex subsidiary or third-party infrastructure."
  },
  {
    "id": "censys",
    "name": "Censys",
    "url": "https://censys.com",
    "cluster": "pure-play",
    "asm_type": ["EASM"],
    "tier": "established",
    "pricing": "$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["mid-market", "enterprise"],
    "integrations": ["SIEM", "SOAR", "ITSM", "Splunk", "ServiceNow"],
    "description": "Censys is the reference standard for internet-scale asset discovery, built on continuous scanning of the full IPv4 and IPv6 internet across 100+ ports and 40+ services. The platform has migrated from its legacy search architecture to a unified Censys Platform powered by CenQL (Censys Query Language), with a natural-language Censys Assistant interface for querying attack surfaces. Data quality and coverage breadth remain the highest in the category — a function of origins in academic research at the University of Michigan. Censys data is frequently used as the discovery engine underneath other commercial platforms, which is a useful signal about where the consolidators' coverage falls short. Its weakness is structural: it shows what exists on the internet but does not determine organizational ownership, nor does it provide exploitability validation or remediation routing.",
    "best_fit": "Security teams, threat hunters, and GRC analysts whose primary requirement is high-fidelity internet discovery and data quality — researchers, red teams, and organizations building custom exposure programs via API on top of reliable scan data.",
    "strengths": ["Gold standard internet-scale scanning — IPv4, IPv6, 100+ ports, 40+ services", "Research-grade data fidelity with CenQL querying capability", "Natural language querying via Censys Assistant"],
    "watch": "Not an operational EASM platform. Asset attribution, exploitability validation, and remediation routing require external tools or custom development. Legacy Search APIs are sunsetting — organizations with custom scripts or automations built on the old API need to migrate to the new Censys Platform."
  },
  {
    "id": "ionix",
    "name": "IONIX",
    "url": "https://ionix.io",
    "cluster": "pure-play",
    "asm_type": ["EASM"],
    "tier": "challenger",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "full",
    "company_size": ["enterprise"],
    "integrations": ["SIEM", "SOAR", "ITSM", "ServiceNow", "Jira"],
    "description": "IONIX (formerly Cyberpion) differentiates on organizational entity mapping and exploitability validation. Where most EASM platforms discover assets and report exposures, IONIX builds an organizational model first — mapping subsidiaries, acquired companies, and supply chain dependencies — then validates which discovered exposures are actually exploitable from an attacker's perspective, rather than reporting passive enumeration findings. This architecture makes it particularly suited to multi-subsidiary enterprises and organizations with active M&A pipelines where the attack surface spans entities the security team may not fully know about. IONIX operationalizes all five CTEM stages, one of few vendors that can make that claim credibly.",
    "best_fit": "Multi-subsidiary enterprises, organizations with recent or ongoing M&A activity, and security teams that need validated exploitability findings rather than passive enumeration — particularly where digital supply chain exposure is a primary concern.",
    "strengths": ["Organizational entity mapping across subsidiaries and supply chain", "Exploitability validation — confirms which findings are actionable", "Full CTEM operationalization across all five stages"],
    "watch": "Premium pricing reflects the depth of the platform. ROI case is strongest for organizations with complex entity structures; single-entity organizations with clean infrastructure may not need this level of depth."
  },
  {
    "id": "cycognito",
    "name": "CyCognito",
    "url": "https://www.cycognito.com",
    "cluster": "pure-play",
    "asm_type": ["EASM"],
    "tier": "challenger",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["mid-market", "enterprise"],
    "integrations": ["SIEM", "SOAR", "ITSM", "ServiceNow", "Jira", "Splunk"],
    "description": "CyCognito runs automated, unauthenticated active testing at scale — not just passive enumeration — to confirm external reachability and exposure conditions. That distinction is meaningful: passive scanners report what exists; CyCognito attempts to confirm what is actually exposed and reachable from the internet. Prioritization is based on attacker relevance and impact, and the platform validates whether remediation actions actually reduced external exposure, a feedback loop most competitors do not close. It is positioned primarily for directly-owned infrastructure in mid-market and enterprise organizations rather than the complex multi-subsidiary use case where IONIX has a structural advantage.",
    "best_fit": "Mid-market and enterprise security teams that want active exposure validation — confirmed reachability, not just passive enumeration — and remediation feedback loops for directly-owned infrastructure.",
    "strengths": ["Active unauthenticated testing confirms real reachability, not just existence", "Remediation validation — confirms whether fixes actually worked", "Fast onboarding relative to peers"],
    "watch": "Organizational scope is strongest for single-entity or simple structures. Complex multi-subsidiary environments with acquisition history may find IONIX's entity mapping more appropriate."
  },
  {
    "id": "cybel-angel",
    "name": "CybelAngel",
    "url": "https://www.cybelangel.com",
    "cluster": "pure-play",
    "asm_type": ["EASM", "DRPS"],
    "tier": "challenger",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seedless",
    "ctem_alignment": "partial",
    "company_size": ["enterprise"],
    "integrations": ["SIEM", "SOAR", "ITSM"],
    "description": "CybelAngel combines external attack surface management with digital risk protection — dark web monitoring, data leak detection, and credential exposure — in a single platform. Its focus on deep contextual asset mapping, particularly for digital supply chains and third-party dependencies, differentiates it from EASM platforms that concentrate on directly-owned infrastructure. The combined EASM and DRPS architecture is valuable for organizations where third-party and supplier exposure is a primary risk concern alongside their own perimeter, though it introduces a broader scope than organizations focused purely on operational ASM need.",
    "best_fit": "Enterprises with significant third-party and supply chain exposure where digital risk protection — credential monitoring, data leak detection, dark web coverage — needs to sit alongside external asset discovery in a single workflow.",
    "strengths": ["Combined EASM and DRPS in one platform", "Deep digital supply chain and third-party asset mapping", "Dark web monitoring and credential exposure detection"],
    "watch": "Broader scope than pure EASM means evaluation should confirm which capabilities are actually needed. DRPS depth comes at the cost of some EASM operational depth compared to pure-play discovery specialists."
  },
  {
    "id": "bitsight",
    "name": "Bitsight",
    "url": "https://www.bitsight.com",
    "cluster": "risk-rating",
    "asm_type": ["EASM", "DRPS"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seeded",
    "ctem_alignment": "none",
    "company_size": ["enterprise"],
    "integrations": ["GRC-platforms", "SIEM", "ITSM", "procurement-tools"],
    "description": "Bitsight is a security ratings platform that has built external attack surface monitoring capabilities alongside its core vendor risk management and cyber insurance products. Its architecture answers a different question than operational EASM: not 'what can an attacker exploit in my environment right now' but 'how does my external security posture compare to industry benchmarks, and how do my vendors score.' That framing is valuable for board reporting, insurance underwriting, and third-party vendor assessments. It is less useful for security operations teams who need actionable findings routed to remediation. Bitsight's ASM capabilities function as an extension of its ratings model rather than as a standalone discovery engine.",
    "best_fit": "GRC teams, risk management functions, and organizations whose primary ASM use case is vendor risk assessment, board-level reporting, or cyber insurance rather than operational security team workflows.",
    "strengths": ["Established vendor risk management and security ratings ecosystem", "Board-ready risk reporting and benchmarking", "Strong position in cyber insurance and compliance use cases"],
    "watch": "Not a substitute for operational EASM. Discovery depth and exploitability context are meaningfully shallower than purpose-built EASM platforms. Understand which question you are actually trying to answer before evaluating."
  },
  {
    "id": "securityscorecard",
    "name": "SecurityScorecard",
    "url": "https://securityscorecard.com",
    "cluster": "risk-rating",
    "asm_type": ["EASM", "DRPS"],
    "tier": "established",
    "pricing": "$$$",
    "deployment": ["cloud"],
    "discovery_method": "seeded",
    "ctem_alignment": "none",
    "company_size": ["enterprise"],
    "integrations": ["GRC-platforms", "SIEM", "ITSM", "procurement-tools"],
    "description": "SecurityScorecard built its market position on security ratings for third-party vendor assessment and cyber insurance, and has extended into attack surface monitoring from that foundation. Like Bitsight, its architecture is optimized for scoring and benchmarking rather than operational discovery and remediation. The platform provides continuous monitoring of an organization's own attack surface alongside vendor portfolios, with findings surfaced in the context of ratings and risk scores. The procurement and vendor risk management workflows are the strongest use case. Security operations teams looking for actionable, exploitability-validated findings will find the operational depth limited relative to dedicated EASM platforms.",
    "best_fit": "Risk management and procurement teams running vendor risk programs who want their own external posture monitored in the same platform they use to assess third-party vendors.",
    "strengths": ["Established third-party vendor risk management ecosystem", "Continuous monitoring of own and vendor attack surfaces in one view", "Risk scoring context useful for procurement and compliance decisions"],
    "watch": "Operational EASM depth is limited. Discovery accuracy and exploitability validation trail dedicated EASM platforms. Best evaluated as a risk management tool, not a security operations tool."
  }
]